2025-06-10 21:53:13.336 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2025-06-10 21:53:17.577 ERROR (SyncWorker_2) [pyicloud.base] Authentication required for Account. (421)
2025-06-10 21:53:19.410 ERROR (SyncWorker_2) [homeassistant.components.icloud.account] Your password for 'finleywright04@outlook.com' is no longer working; Go to the Integrations menu and click on Configure on the discovered Apple iCloud card to login again
2025-06-10 21:53:55.443 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.224 (192.168.0.224). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0)
2025-06-10 21:53:55.490 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.224 (192.168.0.224). Requested URL: '/api/websocket'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0)
2025-06-10 21:55:21.104 ERROR (MainThread) [frontend.js.modern.202410022] Failed to format translation for key 'component.icloud.config.step.reauth_confirm.title' in language 'en-GB'. Error: The intl string context variable "name" was not provided to the string "Authentication expired for {name}"
2025-06-10 21:56:05.808 ERROR (MainThread) [frontend.js.modern.202410022] Uncaught error from Firefox 139.0 on Windows 10
TypeError: i is undefined
_keyFunction (src/panels/config/integrations/dialog-add-integration.ts:471:4)
item (src/virtualize.ts:116:53)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:816:23)
2025-06-10 21:56:05.808 ERROR (MainThread) [frontend.js.modern.202410022] Uncaught error from Firefox 139.0 on Windows 10
TypeError: i is undefined
_keyFunction (src/panels/config/integrations/dialog-add-integration.ts:471:4)
item (src/virtualize.ts:116:53)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:816:23)
2025-06-10 22:04:24.425 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry BT HomeHub6DX for upnp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/upnp/__init__.py", line 96, in async_setup_entry
    await device.async_subscribe_services()
  File "/usr/src/homeassistant/homeassistant/components/upnp/device.py", line 208, in async_subscribe_services
    await self._igd_device.async_subscribe_services(auto_resubscribe=True)
  File "/usr/local/lib/python3.12/site-packages/async_upnp_client/profiles/profile.py", line 355, in async_subscribe_services
    new_sid, timeout = await self._event_handler.async_subscribe(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/async_upnp_client/event_handler.py", line 208, in async_subscribe
    raise UpnpResponseError(
async_upnp_client.exceptions.UpnpResponseError: Did not receive HTTP 200 but 412
